ecn_mini/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trade.urls', namespace='trade')),
]

trade/urls.py
from django.urls import path

from .views import matched_order_audit_report, create_order, cor_list, open_orders

app_name = 'trade'

urlpatterns = [
    path('matched-order-audit-report', matched_order_audit_report, name='matched_order_audit_report'),
    path('create-order', create_order, name='create_order'),
    path('', cor_list, name='cor_list'),
    path('open-orders', open_orders, name='open_orders'),
]

trade/models.py
from django.db import models

from base.models import BaseModel
from crm.models import Client, Security

# Create your models here.

TRADE_ORDER_TYPE = (
    ('Buy', 'Buy'),
    ('Sell', 'Sell'),
)

TRADE_STATUS = (
    ('Pending', 'Pending'),
    ('Partial', 'Partial'),
    ('Matched', 'Matched'),
    ('Cancelled', 'Cancelled'),
    ('Market-Cancelled', 'Market-Cancelled'),
    ('Closed', 'Closed'),
)


class ClientOrderRequest(BaseModel):
    tid = models.CharField(max_length=100, unique=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    security = models.ForeignKey(Security, on_delete=models.CASCADE)
    units = models.PositiveIntegerField(default=0)
    matched_qty = models.PositiveIntegerField(default=0)
    volume_per_unit = models.PositiveIntegerField(default=0)
    order_type = models.CharField(max_length=20, choices=TRADE_ORDER_TYPE)
    order_price = models.DecimalField(
        max_digits=20, decimal_places=2)  # price to buy or to sell
    status = models.CharField(
        max_length=30, choices=TRADE_STATUS, default="Pending")

    security_location_code = models.CharField(max_length=250, null=True, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "%s ----  %s" % (self.client.cid, self.security.code)

    @property
    def cid(self):
        return self.client.cid


class MatchedOrder(BaseModel):
    matched_id = models.CharField(max_length=130, unique=True)
    order = models.ForeignKey(
        ClientOrderRequest, on_delete=models.CASCADE, related_name="matchedorders")
    matched_with_order = models.ForeignKey(ClientOrderRequest, on_delete=models.CASCADE,
                                           related_name="matched_with_order")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    matched_units = models.PositiveIntegerField()
    matched_price = models.DecimalField(
        max_digits=20, decimal_places=2, default=0)
    is_processed = models.BooleanField(default=False)
    processed_on = models.DateTimeField(blank=True, null=True)

    total_order_price = models.DecimalField(
        max_digits=20, decimal_places=2, default=0)

    location_breakdown = models.JSONField(null=True, blank=True)
    is_audited = models.BooleanField(default=False)
    audit_note = models.TextField(default='')

    class Meta:
        unique_together = (('order', 'matched_with_order'),)

    def __str__(self):
        return "%s - %s -%s" % (self.order.tid, self.matched_with_order.tid, self.matched_units)

    @property
    def order_type(self):
        return self.order.order_type


class MatchBook(BaseModel):
    buy_tid = models.CharField(max_length=50)
    sell_tid = models.CharField(max_length=50)
    security_code = models.CharField(max_length=20)
    matched_qty = models.PositiveIntegerField()
    matched_price = models.DecimalField(max_digits=20, decimal_places=2)
    matched_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.buy_tid}-{self.sell_tid}"

trade/forms.py
from django import forms

from .models import ClientOrderRequest


class CreateCORForm(forms.ModelForm):
    class Meta:
        model = ClientOrderRequest
        fields = [
            'client', 'security', 'units', 'order_type', 'order_price',
        ]
        widgets = {
            'client': forms.Select(attrs={'class': "form-control"}),
            'security': forms.Select(attrs={'class': "form-control"}),
            'units': forms.NumberInput(attrs={'class': "form-control"}),
            'order_price': forms.TextInput(attrs={'class': "form-control"}),
            'order_type': forms.Select(attrs={'class': "form-control"}),
        }

trade/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.utils.crypto import get_random_string
from django.contrib import messages

from .forms import CreateCORForm
from .models import ClientOrderRequest, MatchedOrder
from .utils import get_open_trades, clean_trades

# Create your views here.


def matched_order_audit_report(request):
    context = {
        'objects': MatchedOrder.objects.all()
    }
    return render(request, 'trade/index.html', context)


def create_order(request):

    if request.method == 'POST':
        form = CreateCORForm(request.POST)
        if form.is_valid():
            cor = form.save(commit=False)
            cor.tid = get_random_string(10, "0123456789")
            cor.volume_per_unit = cor.security.volume_per_unit
            cor.save()
            messages.success(request, f"You have place a {cor.order_type.lower()} order for {cor.security} successfully")
            return HttpResponseRedirect(reverse('trade:cor_list'))
    else:
        form = CreateCORForm()

    context = {
        'form': form,
    }
    return render(request, 'trade/create_order.html', context)


def cor_list(request):
    context = {
        'cors': ClientOrderRequest.objects.all(),
    }
    return render(request, 'trade/order_list.html', context)


def open_orders(request):
    context = {
        'open_orders': clean_trades(get_open_trades()),
    }
    return render(request, 'trade/open_order_list.html', context)

trade/templates/trade/create_order.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Afex Retreat : Hackathon</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- {% static 'request_dashboard/public/icons/note-green.svg'%} -->
    <!--===============================================================================================-->
    <link
            rel="icon"
            type="image/png"
            href="{% static 'images/icons/favicon.ico' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/animate/animate.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/select2/select2.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/util.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/main.css' %}"
    />

    <style>
        label {
            display: inline-block;
            margin-bottom: 0.5rem;
            margin-top: 20px;
        }
    </style>

    <style>
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }
    </style>
    <!--===============================================================================================-->
</head>

<body>
{% include 'trade/navbar.html' %}
{% include 'trade/messages.html' %}

<div class="limiter">
    <div class="container-table100">
        <form method="post" action="">{% csrf_token %}
            <h5 class="mb-3">Create Order Request</h5>
            <div class="card">
                <div class="card-header">
                    <h6>Enter Order Details</h6>
                </div>
                <div class="card-body">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

trade/templates/trade/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Afex Retreat : Hackathon</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- {% static 'request_dashboard/public/icons/note-green.svg'%} -->
    <!--===============================================================================================-->
    <link
            rel="icon"
            type="image/png"
            href="{% static 'images/icons/favicon.ico' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/animate/animate.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/select2/select2.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/util.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/main.css' %}"
    />
    <!--===============================================================================================-->

    <style>
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }
    </style>
</head>

<body>
{% include 'trade/navbar.html' %}
{% include 'trade/messages.html' %}
<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100 ver2 m-b-110">
                <div class="card-header">
                    <h4>Matched Orders</h4>
                </div>
                <div class="card-body">
                    <table data-vertable="ver2">
                        <thead>
                        <tr class="row100 head">
                            <th class="column100 column1" data-column="column1"></th>
                            <th class="column100 column2" data-column="column2">S/N</th>
                            <th class="column100 column3" data-column="column3">
                                Matched ID
                            </th>
                            <th class="column100 column4" data-column="column4">
                                Order Type
                            </th>
                            <th class="column100 column5" data-column="column5">
                                Matched Units
                            </th>
                            <th class="column100 column6" data-column="column6">
                                Matched Price
                            </th>
                            <th class="column100 column7" data-column="column7">
                                Audited
                            </th>
                            <th class="column100 column8" data-column="column8">
                                Audit Note
                            </th>
                            <th class="column100 column8" data-column="column8">
                               Created
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in objects %}
                            <tr class="row100">
                                <td class="column100 column1" data-column="column1"></td>
                                <td class="column100 column2" data-column="column2">{{ forloop.counter }}</td>
                                <td class="column100 column3" data-column="column3">{{ object.matched_id }}</td>
                                <td class="column100 column4" data-column="column4">{{ object.order_type }}</td>
                                <td class="column100 column5" data-column="column5">{{ object.matched_units }}</td>
                                <td class="column100 column6" data-column="column6">{{ object.matched_price }}</td>
                                <td class="column100 column6" data-column="column6">{{ object.is_audited|yesno|title }}</td>
                                <td class="column100 column6" data-column="column6">{{ object.audit_note|default:"N/A" }}</td>
                                <td class="column100 column6" data-column="column6">{{ object.created }}</td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

trade/templates/trade/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible">
            <h5>
                {{ message.tags|title }}!</h5>
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

trade/templates/trade/navbar.html
<div class="topnav">
    <a class="active" href="{% url 'trade:cor_list' %}">Order Request List</a>
    <a href="{% url 'trade:create_order' %}">Create Order</a>
    <a href="{% url 'trade:matched_order_audit_report' %}">Audit Report</a>
    <a href="{% url 'trade:open_orders' %}">Open Orders</a>
</div>

trade/templates/trade/open_order_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Afex Retreat : Hackathon</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- {% static 'request_dashboard/public/icons/note-green.svg'%} -->
    <!--===============================================================================================-->
    <link
            rel="icon"
            type="image/png"
            href="{% static 'images/icons/favicon.ico' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/animate/animate.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/select2/select2.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/util.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/main.css' %}"
    />
    <!--===============================================================================================-->

    <style>
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-deopen_orderation: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }
    </style>
</head>

<body>
{% include 'trade/navbar.html' %}
{% include 'trade/messages.html' %}
<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100 ver2 m-b-110">
                <div class="card-header">
                    <h4>Open Orders</h4>
                    <small>This data is being pulled from the in-memory database</small>
                </div>
                <div class="card-body">
                    <table data-vertable="ver2">
                        <thead>
                        <tr class="row100 head">
                            <th>TID</th>
                            <th>Client</th>
                            <th>Security</th>
                            <th>Order Type</th>
                            <th>Order Price</th>
                            <th>Total Units</th>
                            <th>Total Matched Units</th>
                            <th>Status</th>
                            <th>Created</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for open_order in open_orders %}
                            <tr class="row100">
                                <td class="column100 column1"
                                    data-column="column1">{{ open_order.tid }}</td>
                                <td class="column100 column2"
                                    data-column="column2">{{ open_order.cid }}</td>
                                <td class="column100 column3"
                                    data-column="column3">{{ open_order.security_code }}</td>
                                <td class="column100 column4"
                                    data-column="column4">{{ open_order.order_type }}</td>
                                <td class="column100 column5"
                                    data-column="column5">{{ open_order.order_price }}</td>
                                <td class="column100 column6"
                                    data-column="column6">{{ open_order.units }}</td>
                                <td class="column100 column7"
                                    data-column="column7">{{ open_order.matched_qty }}</td>
                                <td class="column100 column8"
                                    data-column="column8">{{ open_order.status }}</td>
                                <td class="column100 column9"
                                    data-column="column9">{{ open_order.created }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

trade/templates/trade/order_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Afex Retreat : Hackathon</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- {% static 'request_dashboard/public/icons/note-green.svg'%} -->
    <!--===============================================================================================-->
    <link
            rel="icon"
            type="image/png"
            href="{% static 'images/icons/favicon.ico' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/animate/animate.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/select2/select2.min.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}"
    />
    <!--===============================================================================================-->
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/util.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/main.css' %}"
    />
    <!--===============================================================================================-->

    <style>
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }
    </style>
</head>

<body>
{% include 'trade/navbar.html' %}
{% include 'trade/messages.html' %}
<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100 ver2 m-b-110">
                <div class="card-header">
                    <h4>Order Request List</h4>
                    <small><a href="{% url 'trade:create_order' %}" class="btn btn-success">Create Order Request</a>
                    </small>
                </div>
                <div class="card-body">
                    <table data-vertable="ver2">
                        <thead>
                        <tr class="row100 head">
                            <th>TID</th>
                            <th>Client</th>
                            <th>Security</th>
                            <th>Order Type</th>
                            <th>Order Price</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cor in cors %}
                            <tr class="row100">
                                <td class="column100 column1"
                                    data-column="column1">{{ cor.tid }}</td>
                                <td class="column100 column2"
                                    data-column="column2">{{ cor.client.cid }}</td>
                                <td class="column100 column3"
                                    data-column="column3">{{ cor.security }}</td>
                                <td class="column100 column4"
                                    data-column="column4">{{ cor.order_type }}</td>
                                <td class="column100 column5"
                                    data-column="column5">{{ cor.order_price }}</td>
                                <td class="column100 column6"
                                    data-column="column6">{{ cor.get_status_display }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>